//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Demo.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Demo.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ tối đa 255 kí tự.
        /// </summary>
        public static string UserMsg_Address255 {
            get {
                return ResourceManager.GetString("UserMsg_Address255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản nhân viên tối đa 25 kí tự.
        /// </summary>
        public static string UserMsg_BankAccoutMax25 {
            get {
                return ResourceManager.GetString("UserMsg_BankAccoutMax25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chi nhánh ngân hàng tối đa 255 kí tự.
        /// </summary>
        public static string UserMsg_BankBranchMax255 {
            get {
                return ResourceManager.GetString("UserMsg_BankBranchMax255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng tối đa 255 kí tự.
        /// </summary>
        public static string UserMsg_BankNameMax255 {
            get {
                return ResourceManager.GetString("UserMsg_BankNameMax255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string UserMsg_DateOfBirthMax {
            get {
                return ResourceManager.GetString("UserMsg_DateOfBirthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ  phận không được để trống.
        /// </summary>
        public static string UserMsg_DepartmentEmpty {
            get {
                return ResourceManager.GetString("UserMsg_DepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_DupEmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_DupEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên bị trùng.
        /// </summary>
        public static string UserMsg_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email tối đa 100 kí tự.
        /// </summary>
        public static string UserMsg_EmailMax100 {
            get {
                return ResourceManager.GetString("UserMsg_EmailMax100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống.
        /// </summary>
        public static string UserMsg_EmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên viên phải kết thúc băng chữ số.
        /// </summary>
        public static string UserMsg_EmployeeCodeEndNum {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeCodeEndNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đa 20 kí tự.
        /// </summary>
        public static string UserMsg_EmployeeCodeMax20 {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeCodeMax20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống.
        /// </summary>
        public static string UserMsg_EmployeeDepartment {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được để trống.
        /// </summary>
        public static string UserMsg_EmployeeFullNameEmpty {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeFullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên tối đa 100 kí tự.
        /// </summary>
        public static string UserMsg_FullNameMax100 {
            get {
                return ResourceManager.GetString("UserMsg_FullNameMax100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân tối đa 25 kí tự.
        /// </summary>
        public static string UserMsg_IdentityNumberMax25 {
            get {
                return ResourceManager.GetString("UserMsg_IdentityNumberMax25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm chứng minh nhân dân tối đa 50 kí tự.
        /// </summary>
        public static string UserMsg_IdentityPlaceMax50 {
            get {
                return ResourceManager.GetString("UserMsg_IdentityPlaceMax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên.
        /// </summary>
        public static string UserMsg_NotFound {
            get {
                return ResourceManager.GetString("UserMsg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định tối đa 50 kí tự.
        /// </summary>
        public static string UserMsg_PhoneNumberMax50 {
            get {
                return ResourceManager.GetString("UserMsg_PhoneNumberMax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí nhân viên tối đa 255 kí tự.
        /// </summary>
        public static string UserMsg_PositionName255 {
            get {
                return ResourceManager.GetString("UserMsg_PositionName255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuê tối đa 255 kí tự.
        /// </summary>
        public static string UserMsg_TaxMax255 {
            get {
                return ResourceManager.GetString("UserMsg_TaxMax255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại tối đa 50 kí tự.
        /// </summary>
        public static string UserMsg_TelePhoneNumberMax50 {
            get {
                return ResourceManager.GetString("UserMsg_TelePhoneNumberMax50", resourceCulture);
            }
        }
    }
}
